#
# Copyright (C) 2012 Academic and Research Network of Slovenia (Arnes).
# All Rights Reserved.
# 
# This file is part of IRR Cacher.
# 
# IRR Cacher is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, version 2.0 of the License.
# 
# IRR Cacher is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
# 
# You should have received a copy of the GNU General Public License v2.0
# along with IRR Cacher.  If not, see:
# 
# http://www.gnu.org/licenses/gpl-2.0.html
#

# This library returns data from a data file generated by Net::IRR::Cache.

package Net::IRR::Read;

use strict;
use warnings;

use Carp;
use YAML::Tiny;

BEGIN {
	our ($VERSION);
	$VERSION = 0.10;
}

# where to find cache files
our $Data_Dir = '/tmp';
our $Cache_Prefix = 'irr-cache';


my $asn = '';
my $afi = '';
my $loaded = 0;
my $asn_list = [];
my $route_list = [];


sub get_asn_string {
	return join(', ', @{ get_asn_list(@_) });
}


sub get_asn_list {
	_read_args(@_);
	if ($loaded == 0) {
		_load_data_file();
	}
	return $asn_list;
}


sub get_route_string {
	return join(', ', @{ get_route_list(@_) });
}


sub get_route_list {
	_read_args(@_);
	if ($loaded == 0) {
		_load_data_file();
	}
	return $route_list;
}


# Loads current AS data from irr-data YAML file.
sub _load_data_file {
	my $data_path = $Data_Dir.'/'.$Cache_Prefix.'.'.$afi.'.yaml';
	my $yaml = YAML::Tiny->read( $data_path );
	if (!defined $yaml || !defined $yaml->[0]->{ $asn }) {
		return;
	}
	$asn_list = $yaml->[0]->{ $asn }->{asn_list};
	$route_list = $yaml->[0]->{ $asn }->{route_list};
	$loaded = 1;
}


sub _read_args {
	my %conf = @_;
	if ($conf{asn} ne $asn || $conf{afi} ne $afi) {
		$loaded = 0;
		$asn_list = [];
		$route_list = [];
	}
	$asn = $conf{asn};
	$afi = $conf{afi};
}

1;